# Generated by Django 2.2.27 on 2022-04-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/school_logo.png', upload_to='profile_pics'),
        ),
    ]
