# Generated by Django 2.2.13 on 2022-01-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Correct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('correct_image', models.ImageField(blank=True, default='correct.png', upload_to='correct-paper/')),
                ('answer_image', models.ImageField(blank=True, default='correct.png', upload_to='answer-paper/')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correct',
                'verbose_name_plural': 'Corrects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Sciences', 'Sciences'), ('Grammar', 'Grammar'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Geography', 'Geography'), ('Einglish', 'Einglish'), ('History', 'History'), ('Computer', 'Computer'), ('Physics', 'Physics'), ('Islam', 'Islam'), ('National Education', 'National Education'), ('Statistics', 'Statistics'), ('philosophy', 'philosophy'), ('psychology', 'psychology'), ('Reading', 'Reading'), ('Literary Studies', 'Literary Studies')], max_length=100)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('code', models.CharField(max_length=225)),
                ('qr_code', models.ImageField(blank=True, default='qrcode.png', upload_to='QR-code/')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paper.Class')),
                ('teacher_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paper.Teacher')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
            },
        ),
    ]
