# Generated by Django 2.2.13 on 2022-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('stu_num', models.CharField(max_length=225)),
                ('teacher_name', models.CharField(max_length=225)),
                ('subject', models.CharField(max_length=225)),
                ('qr_code', models.ImageField(blank=True, default='/paper/img/qrcode.png', upload_to='QR-code/')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
            },
        ),
    ]
